### ISSUE TITLE
Parser crashes with KeyError

### ISSUE THREAD

**Issue by fergusq** [Unipisa/diaparser#9]
When trying to run the parser, it crashes with KeyError.

```py
>>> from diaparser.parsers import Parser
>>> parser = Parser.load("fi_tdt.turkunlp")
>>> parser.predict([['Kissa', 'kävelee', 'kadulla', '.']])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iikka/.local/lib/python3.9/site-packages/diaparser/parsers/biaffine_dependency.py", line 129, in predict
    return super().predict(**Config().update(locals()))
  File "/home/iikka/.local/lib/python3.9/site-packages/diaparser/parsers/parser.py", line 191, in predict
    dataset.build(args.batch_size, args.buckets)
  File "/home/iikka/.local/lib/python3.9/site-packages/diaparser/utils/data.py", line 94, in build
    self.loader = DataLoader(dataset=self,
  File "/home/iikka/.local/lib/python3.9/site-packages/diaparser/utils/data.py", line 108, in __init__
    super().__init__(*args, **kwargs)
  File "/home/iikka/.local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 200, in __init__
    if isinstance(dataset, IterableDataset):
  File "/usr/lib64/python3.9/typing.py", line 1114, in __instancecheck__
    if all(hasattr(instance, attr) and
  File "/usr/lib64/python3.9/typing.py", line 1114, in <genexpr>
    if all(hasattr(instance, attr) and
  File "/home/iikka/.local/lib/python3.9/site-packages/diaparser/utils/data.py", line 65, in __getattr__
    return [getattr(sentence, name) for sentence in self.sentences]
  File "/home/iikka/.local/lib/python3.9/site-packages/diaparser/utils/data.py", line 65, in <listcomp>
    return [getattr(sentence, name) for sentence in self.sentences]
  File "/home/iikka/.local/lib/python3.9/site-packages/diaparser/utils/transform.py", line 117, in __getattr__
    return self.values[self.maps[name]]
KeyError: 'register_function'
```

I have Python 3.9.6, pytorch 1.9.0, transformers 4.10.2.

**Comment by fginter** [comment]
This can be fixed by changing transform.py around line 113 to:

```
   def __getattr__(self, name):
        if name in self.__dict__:
            return self.__dict__[name]
        elif name in self.maps:
            return self.values[self.maps[name]]
        else:
            raise AttributeError()
```

**Comment by fginter** [comment]
@fergusq I fixed this downstream now https://github.com/TurkuNLP/Turku-neural-parser-pipeline/issues/34   I didn't notice this issue you opened here.

**Comment by attardi** [comment]
Fixed.
